### ISSUE TITLE
P3D Gives Link Errors on Windows

### ISSUE THREAD

**Issue by ShadowfeindX** [ruby-processing/propane#29]
### Environment

**(jruby -v):** 
```
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.171-b11 on 1.8.0_171-b11 +jit [mswin32-x86_64]
```
**(java -version):**
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
**(propane --version):**
```
Propane version 2.7.2
JRuby version 9.2.0.0
```
**(uname -a):**
```
MINGW64_NT-10.0 DESKTOP-22BGKLK 2.8.0(0.309/5/3) 2017-05-19 13:17 x86_64 Msys
```

### Problem 
Hello!
I wanted to try out propane so I made a test script
```ruby
require 'propane'

class Test < Propane::App

  def settings
    size 600, 600, P3D
  end

  def setup
    sketch_title 'Test'
  end

  def draw
    background 0
    w = 10
    grid(width, height) { |x, y|
      rect x*w, y*w, w, w
    }
  end
end

Test.new
```
Unfortunately it gave me some errors like these (I changed the directory name to `$PWD` because it was rather long and is actually my current working directory so...)
```
Unhandled Java exception: java.lang.UnsatisfiedLinkError: Can't load library: $PWD\natives\windows-amd64\\gluegen-rt.dll
java.lang.UnsatisfiedLinkError: Can't load library: $PWD\natives\windows-amd64\\gluegen-rt.dll
```
```
Unhandled Java exception: java.lang.UnsatisfiedLinkError: Can't load library: $PWD\natives\windows-amd64\\nativewindow_awt.dll
java.lang.UnsatisfiedLinkError: Can't load library: $PWD\natives\windows-amd64\\nativewindow_awt.dll
```

### Solution?
After some snooping I found `lib/export.txt` and notice some things.
```
# stuff from file

application.windows32=core.jar,jogl-all.jar,gluegen-rt.jar,jogl-all-natives-windows-i586.jar,gluegen-rt-natives-windows-i586.jar
application.windows64=core.jar,jogl-all.jar,gluegen-rt.jar,jogl-all-natives-windows-amd64.jar,gluegen-rt-natives-windows-amd64.jar

# stuff from file
```

So, these files are exported, but actually the natives are not in the directory at all.
Only natives for mac and linux.
After downloading them and adding them manually I still get an error.

Then I noticed that the `jogl-all` and `gluegen-rt` have their version numbers in the filenames (like `jogl-all-2.3.2.jar`), but not in the export file so I change the filenames and now it runs without the errors.

I'm not sure when exactly these files are downloaded by the gem or if there are any other references to these files so I can't offer a better solution other than doing it manually like this.

Let me know if there is any additional testing or some such I can do to help.

***Cheers!***

**Comment by monkstone** [comment]
@ShadowfeindX Originally I was only targeting Linux and MacOS with propane, it seems that processing on MacOS might be hitting buffers for a variety of reasons (largely because of think different crap, but more recently Apple have declared they will be dropping opengl support).  Propane has always been somewhat experimental but @jtoy at least found a use for it. It also provided a leaping point for `picrate` ruby-processing on raspberrypi except I haven't yet got opengl to work on `picrate` at present, _yet JRubyArt works quite well_. I think I'd be quite happy to support Windows but had always thought Mac users to be the ruby fans and Windows users more likely to favour python.

**Comment by ShadowfeindX** [comment]
I don't really like python for a large variety of reasons so I've been bouncing between Julia for *scientific* stuff and Ruby for....everything else.

I do most of my projects/development on Windows and Linux (mainly because I don't have a Mac) so I'd be happy to help with testing and adding features and such. Just point me in the right direction captain!

**Comment by monkstone** [comment]
@ShadowfeindX The way I download and include jogamp jars is using maven, specifically a [polyglot version](https://github.com/ruby-processing/propane/blob/master/pom.rb) that requires a `.mvn` folder. Then I need to specify in the `propane.gemspec` the jars to be included (since `.gitignore` specifically excludes jars) which are not part of the github distro. In general it is good idea to avoid including binaries in github, as old versions persist and can lead to horrendous problems processing.org repo was huge, I kept telling ben fry but he would have none of it (like an unreformed alcoholic). Eventually they split repo https://github.com/processing/processing/wiki/Repositories but I'm not sure they really learned their lesson, hosting jars on maven would have been so much easier. At the moment we rely on co-worker @poqudrof to maintain binaries at maven central. You may have a point about version numbers of jars, maybe that's why opengl on picrate isn't working, but here the version name of folders in the  jars containing binaries might be also be an issue. I could easily hack up version to test on Windows, which might be best way forward in first instance.

**Comment by ShadowfeindX** [comment]
I'm not super familiar with maven, but can you specifically include jars programatically? If not, you could store the jars as releases on the repo and then download them after your os check so that you don't download unnecessary jars onto users' systems.

Also so far your build is working on windows so you might not need a new version. Except for like....the entire build and library include process that uses shell commands because you know, windows users generally don't have a terminal.

I can write a system agnostic version of that stuff if you want though. Not sure if there are tests for that.

**Comment by monkstone** [comment]
@ShadowfeindX The way it works is that only the developer downloads the jogl jars, this done once to compile and secondly they are copied as a dependency into the lib folder. Now our gemspec would initially exclude these jars (as not being part of git) so we have to specifically add them. So the gem gets built with all the jars, so everyone that gets the gem gets all the jars. I would also need to add in check for windows binaries for other libraries that load natives (by convention in a folder) eg sound and video, I don't know whether it is safe to default to 64bit binaries on modern windows as with linux, the raspberrypi is an anomaly. It would be nice to post install jars (as we do with jruby-complete, but you can't use wget on maven central).

**Comment by ShadowfeindX** [comment]
@monkstone I think only supporting 64bit Windows is a good starting point considering Windows is moving towards 64 only support itself. The main issues I came across when trying to install and run on my Desktop was the `vendors/Rakefile` which did not run at all because Windows Command Line has no concept of most shell commands and also depends on `wget` which, even when installed on my system through my term emulator, it did not find.

I had an idea for how to handle both of those issues, but I would rather remove the dependency on the shell and `wget` altogether from the codebase. That way you could post-install the jars as you said while also getting a functioning Windows version in the process. I already have a propane fork (mainly to add the `-- watch` command from JRubyArt and to see if I could get bare sketches to work) so I will do some tinkering there and see if I can get anything concrete and testable to work.

Is there some specific branch here that I should be making a PR towards or is using `master` as a base okay? I'm not sure the difference between `master` and `stable` right now and I don't want to get in the way of any of your Raspberry Pi stuff.

**Comment by monkstone** [comment]
@ShadowfeindX Don't worry about raspberry-pi that's a separate project https://github.com/ruby-processing/PiCrate, stable is like a safety belt so a PR against master would be best.

**Comment by monkstone** [comment]
@ShadowfeindX can you give latest release propane-2.9.1 a go

**Comment by monkstone** [comment]
There is possibility that AdoptJDK will fix this it does on linux.

**Comment by monkstone** [comment]
This should be fixed if people use either adoptopenjdk or ibm java
